# Shell variables
# Generated by 'wal'
wallpaper='/home/neurokrem/Slike/Slike/Wallpaper/Crtani/jutro.jpg'

# Special
background='#03142D'
foreground='#d7d2ce'
cursor='#d7d2ce'

# Colors
color0='#03142D'
color1='#ECB079'
color2='#1F6E8B'
color3='#5E7089'
color4='#2D94A7'
color5='#5AA5B1'
color6='#58BDC8'
color7='#d7d2ce'
color8='#969390'
color9='#ECB079'
color10='#1F6E8B'
color11='#5E7089'
color12='#2D94A7'
color13='#5AA5B1'
color14='#58BDC8'
color15='#d7d2ce'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
