--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/neurokrem/Slike/Slike/Wallpaper/Crtani/jutro.jpg"

-- Special
background="#03142D"
foreground="#d7d2ce"
cursor="#d7d2ce"

-- Colors
color0="#03142D"
color1="#ECB079"
color2="#1F6E8B"
color3="#5E7089"
color4="#2D94A7"
color5="#5AA5B1"
color6="#58BDC8"
color7="#d7d2ce"
color8="#969390"
color9="#ECB079"
color10="#1F6E8B"
color11="#5E7089"
color12="#2D94A7"
color13="#5AA5B1"
color14="#58BDC8"
color15="#d7d2ce"
