#!/bin/bash
set -euo pipefail

sudo apt update
sudo apt install -y \
bridge-utils \
ca-certificates \
cargo \
cmake \
code \
cpu-checker \
cron \
curl \
discord \
distro-info \
dkms \
dmg2img \
docker-compose-v2 \
fonts-arphic-ukai \
fonts-arphic-uming \
fonts-noto-cjk \
fonts-noto-cjk-extra \
fonts-noto-ui-core \
gnome-calculator \
gnome-video-effects \
gnome-weather \
gnupg \
gparted \
htop \
hunspell-fr \
hyphen-de \
hyphen-en-ca \
hyphen-en-gb \
hyphen-en-us \
hyphen-es \
hyphen-fr \
hyphen-it \
hyphen-pt-br \
hyphen-pt-pt \
hyphen-ru \
ibus-chewing \
ibus-table-cangjie3 \
ibus-table-cangjie5 \
ibus-table-quick-classic \
ibus-table-wubi \
init \
inxi \
isc-dhcp-common \
krita \
language-pack-ar \
language-pack-de \
language-pack-en \
language-pack-es \
language-pack-fr \
language-pack-it \
language-pack-ja \
language-pack-pt \
language-pack-ru \
language-pack-zh-hans \
language-pack-zh-hant \
libbpf0 \
libconfig++9v5 \
libconfig++9v5:i386 \
libdbus-1-3:i386 \
libdns-export1110 \
libestr0 \
libfastjson4 \
libffado2 \
libffado2:i386 \
libfontconfig1-dev \
libgl1-mesa-dri:i386 \
libisc-export1105 \
libllvm15 \
libllvm15:i386 \
libmpdec3 \
libmysofa1:i386 \
libmysqlclient-dev \
libnetplan0 \
libpop-upgrade-gtk \
libprocps8 \
libsdl2-2.0-0:i386 \
libsigc++-2.0-0v5:i386 \
libsqlite3-0:i386 \
libunistring2 \
libvirt-clients \
libvirt-daemon \
libvirt-daemon-system \
libvulkan1:i386 \
libxcb-xfixes0-dev \
libxkbcommon-dev \
libxml++2.6-2v5 \
libxml++2.6-2v5:i386 \
libyaml-dev \
logrotate \
mesa-utils \
mesa-vulkan-drivers \
mesa-vulkan-drivers:i386 \
mokutil \
mythes-ar \
mythes-de \
mythes-de-ch \
mythes-en-au \
mythes-en-us \
mythes-es \
mythes-fr \
mythes-it \
mythes-pt-pt \
mythes-ru \
nautilus-sendto \
ncdu \
netcat-openbsd \
network-manager-pptp-gnome \
nmap \
p7zip-full \
piper \
plocate \
pop-desktop \
python3-mongoengine \
python3-motor \
python3-netifaces \
python3-pip \
python3-pymongo \
python-mongoengine-doc \
qemu-system \
qemu-system-x86 \
qemu-utils \
ratbagd \
refind \
remmina \
rsyslog \
sessioninstaller \
software-properties-common \
stacer \
steam-installer \
system76-acpi-dkms \
system76-dkms \
system76-io-dkms \
timeshift \
tmux \
ubuntu-advantage-tools \
ubuntu-minimal \
ubuntu-standard \
uml-utilities \
vim-common \
vim-tiny \
virtinst \
virt-manager \
wine \
wine32:i386 \
wine64 \
winetricks \
wofi \
xrdp \
xxd

# kraj